### ISSUE TITLE
Restore tab does not show correct filesystem directory tree

### ISSUE THREAD

**Issue by dev-zero** [stepping-stone/sepiola#58]
See screenshot:

![screenshot_win7_2016-11-22_23 42 32](https://cloud.githubusercontent.com/assets/11307/20545078/66fb0f06-b10d-11e6-8626-850d70774281.png)

- The drive does not have a name (should be `c:`)
- ` testdir` should be below the drive

... but when selecting the drive, `testdir` gets selected as well.

**Comment by philippoehler** [comment]
![image](https://cloud.githubusercontent.com/assets/17530454/20599805/85d73a46-b250-11e6-9c78-29f457180dd3.png)

It seams that this issue was inherited from previous version. 
* Tested version: `sepiola-2.3.5-5-g0c91379-win32.exe`
* Supplier: https://jenkins.stepping-stone.ch/download/sepiola/
* Environment: Windows7, 32Bit

**Comment by dev-zero** [comment]
ok, re-target for v2.5

**Comment by philippoehler** [comment]
Moved this issue back to code because there is still a problem with several drives.

**Comment by dev-zero** [comment]
confirmed to be fixed in 2.5.0.rc0
